name = "SynPUF"
uuid = "fb2237d2-7efa-11e9-3e06-4334625df129"
authors = ["Clark Evans <cce@clarkevans.com>"]
version = "0.1.0"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"

[extras]
NarrativeTest = "9563631e-acd4-5dd8-bebb-4cf36518960d"

[compat]
julia = "1"
DataDeps = "0.6.2"

[targets]
test = ["NarrativeTest"]
